### ISSUE TITLE
Can't work with Laravel6

### ISSUE THREAD

**Issue by bolechen** [mikeerickson/phpunit-pretty-result-printer#153]
```bash
$ laravel new blog
$ cd blog
$ composer require --dev codedungeon/phpunit-result-printer
$ phpunit --printer=Codedungeon\\PHPUnitPrettyResultPrinter\\Printer
```

have error

```
 ~/blog/ phpunit --printer=Codedungeon\\PHPUnitPrettyResultPrinter\\Printer

PHPUnit Pretty Result Printer 0.26.2 by Codedungeon and contributors.
==> Configuration: ~/blog/vendor/codedungeon/phpunit-result-printer/src/phpunit-printer.yml

PHPUnit 8.4.3 by Sebastian Bergmann and contributors.


 ==> ExampleTest                PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php:979
Stack trace:
#0 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php(813): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php(682): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php(630): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(170): Illuminate\Foundation\A in /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 979

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php:979
Stack trace:
#0 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php(813): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php(682): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php(630): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(170): Illuminate\Foundation\A in /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 979
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php:979
Stack trace:
#0 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php(813): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php(682): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php(630): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(170): Illuminate\Foundation\A in /Users/avenger/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 979
```

**Comment by mikeerickson** [comment]
@bolechen i have used with many Laravel 6 based applications, including using the steps you have outlined above (using Laravel 6.2) and am not able to reproduce you reported issue.  What version of Laravel was used to produce this error.

**Comment by bolechen** [comment]
sorry, is my mistake.

when i run with local phpunit, it ok

```
vendor/bin/phpunit --printer=Codedungeon\\PHPUnitPrettyResultPrinter\\Printer
```
