### ISSUE TITLE
Report writing appeasrs correctly, but then throws an error

### ISSUE THREAD

**Issue by mikeerickson** [mikeerickson/phpunit-pretty-result-printer#40]
With version >= 0.7 the report writer will correctly display, however, it throws an error upon completion

```
Uncaught TypeError: Return value of Codedungeon\PHPUnitPrettyResultPrinter\Printer::writeProgress() must be an instance of Codedungeon\PHPUnitPrettyResultPrinter\void, none returned in /var/www/mfour_docker/vendor/codedungeon/phpunit-result-printer/src/Printer.php:129
Stack trace:
#0 /var/www/mfour_docker/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php(536): Codedungeon\PHPUnitPrettyResultPrinter\Printer->writeProgress('.')
#1 /var/www/mfour_docker/vendor/phpunit/phpunit/src/Framework/TestResult.php(399): PHPUnit_TextUI_ResultPrinter->endTest(Object(tests\Mfour\Unit\SanitizerTest), 0.025444030761719)
#2 /var/www/mfour_docker/vendor/phpunit/phpunit/src/Framework/TestResult.php(889): PHPUnit_Framework_TestResult->endTest(Object(tests\Mfour\Unit\SanitizerTest), 0.025444030761719)
#3 /var/www/mfour_docker/vendor/phpunit/phpunit/src/Framework/TestCase.php(868): PHPUnit_Framework_TestResult->run(Object(tests\Mfour\Unit\SanitizerTest))
#4 /var/www/mfour_docker/vendor/phpunit/phpunit/src/Framework/TestSuite.php(7 in /var/www/mfour_docker/vendor/codedungeon/phpunit-result-printer/src/Printer.php on line 129
root@a6cdc8c35ec5:/var/www/mfour_docker# ./vendor/bin/phpunit tests/Mfour/Unit
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
```

**Comment by mikeerickson** [comment]
Fixed in `0.9.0` release
