### ISSUE TITLE
How do I fix the "Return value must be an instance of Codedungeon\PHPUnitPrettyResultPrinter\void" ?

### ISSUE THREAD

**Issue by ricardoaugusto** [mikeerickson/phpunit-pretty-result-printer#44]
Output is:

```
PHPUnit 6.5.7 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught TypeError: Return value of Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter::startTest() must be an instance of Codedungeon\PHPUnitPrettyResultPrinter\void, none returned in /Users/ra/Developer/l55/vendor/codedungeon/phpunit-result-printer/src/Printer.php:27
Stack trace:
#0 /Users/ra/Developer/l55/vendor/phpunit/phpunit/src/Framework/TestResult.php(395): Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter->startTest(Object(Tests\Routes\UITest))
#1 /Users/ra/Developer/l55/vendor/phpunit/phpunit/src/Framework/TestResult.php(637): PHPUnit\Framework\TestResult->startTest(Object(Tests\Routes\UITest))
#2 /Users/ra/Developer/l55/vendor/phpunit/phpunit/src/Framework/TestCase.php(894): PHPUnit\Framework\TestResult->run(Object(Tests\Routes\UITest))
#3 /Users/ra/Developer/l55/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#4 /Users/ra/Developer/l55/vendor/phpunit/phpunit/src/Tex in /Users/ra/Developer/l55/vendor/codedungeon/phpunit-result-printer/src/Printer.php on line 27

Fatal error: Uncaught TypeError: Return value of Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter::startTest() must be an instance of Codedungeon\PHPUnitPrettyResultPrinter\void, none returned in /Users/ra/Developer/l55/vendor/codedungeon/phpunit-result-printer/src/Printer.php:27
Stack trace:
#0 /Users/ra/Developer/l55/vendor/phpunit/phpunit/src/Framework/TestResult.php(395): Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter->startTest(Object(Tests\Routes\UITest))
#1 /Users/ra/Developer/l55/vendor/phpunit/phpunit/src/Framework/TestResult.php(637): PHPUnit\Framework\TestResult->startTest(Object(Tests\Routes\UITest))
#2 /Users/ra/Developer/l55/vendor/phpunit/phpunit/src/Framework/TestCase.php(894): PHPUnit\Framework\TestResult->run(Object(Tests\Routes\UITest))
#3 /Users/ra/Developer/l55/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#4 /Users/ra/Developer/l55/vendor/phpunit/phpunit/src/Tex in /Users/ra/Developer/l55/vendor/codedungeon/phpunit-result-printer/src/Printer.php on line 27
```

**Comment by mikeerickson** [comment]
I am working on a fix for this very issue. If you install `0.8.2` it should work in the interim

**Comment by mikeerickson** [comment]
Fixed in `0.9.0` release

**Comment by iraklisg** [comment]
@mikeerickson I use `0.9.3` and I am having the same error :confused: 

```
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught TypeError: Return value of Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter::startTest() must be an instance of Codedungeon\PHPUnitPrettyResultPrinter\void, none returned in /var/www/html/vendor/codedungeon/phpunit-result-printer/src/Printer.php:29
Stack trace:
#0 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(395): Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter->startTest(Object(Tests\Feature\Contractuals\HandleApplicantTest))
#1 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(637): PHPUnit\Framework\TestResult->startTest(Object(Tests\Feature\Contractuals\HandleApplicantTest))
#2 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Tests\Feature\Contractuals\HandleApplicantTest))
#3 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#4 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744):  in /var/www/html/vendor/codedungeon/phpunit-result-printer/src/Printer.php on line 29

```

**Comment by mikeerickson** [comment]
@iraklisg this should be all clear now, please install the latest version (we are currently on `0.11.2`)

**Comment by dhddev** [comment]
@mikeerickson I do confirm that using `0.11.2` the package works as expected :+1:

**Comment by iraklisg** [comment]
@mikeerickson indeed version `0.11.2` works as expected :+1:
